version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
  robot-service:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - rabbitmq
